### ISSUE TITLE
New needs to take varargs Options

### ISSUE THREAD

**Issue by akshayjshah** [uber-go/dig#117]
Before we get further into an RC series, `New` needs to take a variadic number of `Option`s, even if we don't yet have any concrete `Option` implementations. Adding this after 1.0 is a breaking change.

**Comment by glibsm** [comment]
I agree, `New` is definitely a contender.

However, I also think it's worth to think about `Provide` and `Invoke` as well, which right now take a single argument. 

I can think of at least one case that `Provide` might have a useful option:

```
c.Provide(newFoo, dig.Override)
```

Which will not error out if a type is present, but rather replace it in the graph.

**Comment by breerly** [comment]
Let's do both.

It seems like a good idea to move away from variadic arguments in dig, since that'll pave way for options at that level as well.

Fx can easily call Provide or Invoke in a loop given it exposes variadic args in `fx.Provide` and `fx.Invoke`.
