### ISSUE TITLE
Improve support for ordered collections

### ISSUE THREAD

**Issue by akshayjshah** [uber-go/dig#128]
Currently, dig doesn't have an elegant way to put an ordered collection into the graph.

Consider middleware: typically, many libraries want to provide instances of a `Middleware` interface, but the order in which the middleware is composed together is critical. (This order-dependence distinguishes middleware from groups/tags, which are discussed in #127.)

Today, each middleware provider would provide a named instance of `Middleware`, and the end user needs to collect and order the named instances. This is cumbersome, and it pushes all the ordering complexity on end users.

Ideally, we'd find a simple, easily-debuggable way for middleware authors to express ordering constraints and have dig automatically order the collection.

**Comment by bayesianmind** [comment]
Suggested impl:
Preprocess to standard topological sort by first converting all 'after' constraints to reversed 'before' constraints. Do topological sort to create an ordering. Randomize the order of modules before doing the topological sort so the constraints are satisfied but the order is otherwise random. This will make any missing constraints more likely to surface.

**Comment by breerly** [comment]
Agree w Ben here - in other words, dig shouldn't be concerned with ordering, that should happen in the layer that cares about it.

Actually, that makes me wonder if dig could provide the 'before' and 'after' constraints generically...

**Comment by akshayjshah** [comment]
@breerly I'm not following - I read @bayesianmind's comment as a proposal for how dig might automatically order collections based on constraints expressed through struct tags.

There's a lot to like about an approach based on topological sorting: it puts all the ordering complexity in the hands of module authors, which lets service owners worry only about the middleware they write themselves.

Of course, this comes with some tradeoffs:

- The proposed sort is unstable, so behavior will change on restarts and won't be consistent across all tasks in a job. Any stabilizing secondary sort (e.g., lexicographic) introduces the possibility of middleware combinations working by accident.
- Different combinations of middleware (or the same combination of middleware with a different mix of versions) may have incompatible constraints. Resolving these problems requires coordinated releases of multiple middlewares.
- This complex behavior happens completely outside the type system, so it's inherently more error-prone.
- Middleware authors need to know about all other middleware that *might* affect their own middleware's correctness so that they can add the proper constraints.

To me, these drawbacks greatly outweigh the benefits. Among a sampling of widely-used DI containers, only [Symfony supports](http://symfony.com/doc/current/service_container/service_decoration.html#decoration-priority) this (and it does so via an explicit z-index-style system). [Unity](https://msdn.microsoft.com/en-us/library/dn178467(v=pandp.30).aspx#sec4), [Dagger](https://google.github.io/dagger//multibindings.html), [Guice](https://github.com/google/guice/wiki/Multibindings), and [Spring](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mvc.html#mvc-handlermapping-interceptor) all avoid this degree of magic.

Our current approach doesn't require service owners to explicitly order the standard, mission-critical middleware (stats, auth, routing, etc) - they simply extend the defaults with their own ordered collection. I'd like to continue with explicit ordering (some done by the top-level modules and some by individual service owners), since we can always introduce more sugar later.

**Comment by breerly** [comment]
Talked offline - I agree dig *shouldnt* have way to order collections/groups/tags, and that we can manage the ordering explicitly in yarpcfx.

**Comment by bayesianmind** [comment]
Akshay I would love to take 30 min and discuss with you on zoom, even if this ends up being solved within yarpcfx. Obviously it's your call I just want to share some of the real world pain we had in a real system at Amazon for a very similar problem.
