### ISSUE TITLE
Can't embed pointers to dig.In/Out

### ISSUE THREAD

**Issue by glibsm** [uber-go/dig#131]
The following e2e test doesn't work:

```go
	t.Run("embedding out pointers works", func(t *testing.T) {
		c := New()
		type A struct{}
		type B struct {
			Out
			A
		}
		type C struct {
			*B // pointer to B which is a dig.In with A
		}
		require.NoError(t, c.Provide(func() C { return C{} }))
		require.NoError(t, c.Invoke(func(A) {}))
	})
```

It works if type C is written to embed type B directly, rather than the pointer to B:

```go
type C struct {
  B // direct embed of type B
}
```

Question is... do we care? `embedsType` function seems to solely focus on structs:

```go
if t.Kind() != reflect.Struct {
  continue
}
```

Should be easy to modify to look at `Elems()` of a pointer instead.

**Comment by abhinav** [comment]
The original implementation tried to stay as narrow as possible in the range
of types it allowed to be `dig.In` structs.

I don't feel strongly about whether we allow pointers except it may introduce
corner cases we haven't accounted for.  We can always add it post 1.0 if
someone has a valid use case for it.

**Comment by glibsm** [comment]
The main corner case that this is going to add is ability to be stuck in a cycle while trying to detect when something is or isn't an In/Out type.

Because it's impossible to declare a cyclical struct right now it's not a problem. However the following code would recurse indefinitely:

```go
type A struct {
  dig.Out
  *A
}
```

I don't think it's worth to spend cycles on this now, but I'm going to leave this as an open issue for a bit until we decide if it's something we want to tackle for 1.0.

**Comment by glibsm** [comment]
The main issue for me is that it's a *silent* failure. In the aforementioned test, it will register `*B` into the graph, which can be really confusing.

We may want to consider either forbidding it outright (to prevent massive cycles), or at least error out.

**Comment by abhinav** [comment]
I didn't realize it was a silent failure. Yeah, we should definitely error out in this cas.e

**Comment by bayesianmind** [comment]
+1 to either supporting this or erroring out. 
We can also improve our messaging for the dig.In case:
Today if have this:
```
type Z  struct{
    dig.In
    SomeType A
}

func Invoke(b *B){}
```
 Invoke will fail saying that *B isn't in the graph. For someone not familar with Dig this seems like dig.In is broken. I'd like to have a better error message directing users to use `B` instead of `*B`.
