### ISSUE TITLE
Take in context.Context as first param into Provide/Invoke

### ISSUE THREAD

**Issue by glibsm** [uber-go/dig#133]
I thought about this a bit in the _context_ (:drum:) of #132.

Want to open this up for a discussion as we're storming towards v1. Does it feel completely out of place to accept context?

## Problem 

While we did make room for `ProvideOption` and `InvokeOption`, neither are currently implemented and I don't see them fulfilling all the future use cases.

At the very least to implement each an additional datastructure for each is going to be required. Something like `provideConfig`, or `provideContext` or `provider` which encapsulates rules an options for a particular Provide call, like hooks, or rules for how to skip frames.

`context.Context` can actually fill some of those roles.

### User-facing API

User-facing consumption of dig is going to suffer due to an additional parameter. I don't think this is a big deal, as we've spun dig to be a library to build frameworks, rather than for direct consumption.

### Fx

Fx API won't be affected, we can keep them as is. That should allow us to smooth over the aforementioned issue.

### Potential confusion

If we start forking between `Options` and `context.Context` it might be confusing what goes where. 

### ???

Are there any more drawbacks?

### Timeouts & cancellation

Invocation on a type can actually take a long time, depending on the size of the graph. I think it would be wise to leave room for timeouts and `context.Context` things.

```go
c := c.New()
// ...
err := c.Invoke(context.WithTimeout(10 * time.Second), func(A,B,C) { ... })
```

### ???

Let me know if I'm missing something

**Comment by glibsm** [comment]
In order to further clarify the problem statement, let me try to provide an example. Lets say I wanted to be able to introspect _what types were inserted into the graph_ as a result of a `Provide` call.

Lets call it a _hook_ and the type signature for it would be something like 

```go
type TypeHook func(types []reflect.Type)
```

So far so good. 

Now, how do I tell a `Provide` function to use it? I'd need to somehow bend the `TypeHook` into a `ProvideOption`. I'd want to do something like:

```go
c := New()
// ...
c.Provide(func(A,B) {}, dig.WithTypeHook(func(types []reflect.Type) {
  fmt.Println(types)
})
```

In order to achieve that I'd have to attach an instance of a `TypeHook` to _some_ sort of a short-lived object for the space of a given Invoke call, which currently doesn't exist.

**Comment by glibsm** [comment]
After thinking through this more and talking with @alsamylkin it looks like we can simulate `context.Context` and other things through Options:

```go
type provider struct {
  context.Context // can actual embed a context, too, so we can satisfy timeouts through options
  th TypeHook
}
```

Then `ProvideOption` can become:

```go
type ProvideOption interface{
  apply(*provider)
}

func WithContext(c context.Context) {
  return ProvideOption(func(c *provider) {
    c.Context = c
  })
}

type WithTypeHook(th TypeHook) {
  return ProvideOption(func(c *provider) {
    c.th = th
  })
}
```

**Comment by alsamylkin** [comment]
My only concern about adding context is concurrency: DIG was explicitly made concurrent unsafe earlier and use of context assumes the we are going to use channels and go routines.

**Comment by breerly** [comment]
I think I'd rather not worry about adding a context for v1.

Lets see how much we can pull off without a context - if we get backed into a corner, I'm totally fine cutting a v2.0 of dig so long as it's transparent to Fx users.

Dig should be *in service* to Fx alone, so I don't think it hurts here not to add this anticipatory API.

**Comment by akshayjshah** [comment]
Agreed with @breerly - if we need to make a breaking change to take a context later, we can easily do so.

**Comment by glibsm** [comment]
Holding off until necessary is ok with me, especially since options can suffice for a lot of the cases that `context.Context` is good for.
