### ISSUE TITLE
Support multiple return object registration

### ISSUE THREAD

**Issue by anuptalwalkar** [uber-go/dig#18]
Currently dig MustRegister takes funcs that return single object or (object, error) for registration in [Provide](https://github.com/uber-go/dig/blob/master/container.go#L61-L89). We need to add support so that users can write functions that need multiple object registration. For example, [tracing initialization](https://github.com/uber-go/fx/blob/dev/tracing/tracer.go#L35)

**Comment by glibsm** [comment]
In other words, right now a constructor with the form:

```
func new(*A, *B) (*C, *D, error) {
...
}
```

is not supported, is very useful.

**Comment by glibsm** [comment]
We should take note that `io.Closer` is often returned by a lot of the Go construction functions. They often take a return type of `(*Type, io.Closer, error)`.

I think the `io.Closer`, much like `error` should have a special meaning in a dig constructor. All the closers should be accumulated and closed in reverse order when the graph is Reset.

That, however, is out of scope of this particular ticket.
