### ISSUE TITLE
How do i use container between the packages?

### ISSUE THREAD

**Issue by ArkadyB** [uber-go/dig#186]
Hi!

I cant seem to understand on how this should work to be used passing service references between the packages.

An example you have provided as simple as i should not need to use of any DI to accomplish this. 

In my case im trying to create container in the main package and then reuse its value in another. Say i have main function that registers service1 instance. I have http router where i`d need to access service1 (already in container) once HandlerFunc is invoked. How would i do it? 

Does the solution mean i need to pass container instance throught the solution?

Thanks for ur help!

**Comment by abhinav** [comment]
Hi, I'm not sure I understand the question entirely. Are you trying to have
something Invoked/Provided while handling an HTTP request? We don't recommend
you do that. Making the container part of the business logic will become a
problem in the future (see also [this comment](https://github.com/uber-go/dig/issues/201#issuecomment-404663152)).

Ideally, you're using dig only inside your main package to wire together and
instantiate long-lived objects. That way you're paying the cost of reflection
only once.

**Comment by abhinav** [comment]
Closing unless there are more questions.
