### ISSUE TITLE
How stable master branch is?

### ISSUE THREAD

**Issue by constant-null** [uber-go/dig#187]
Hello, i want to use this package directly using go get, so i can make go getable app without vendors under vsc and etc. 
gopkg.in didn't work (because of "internals" it looks like), so i was thinking, is master stable enough to use it?

**Comment by akshayjshah** [comment]
We don't make any guarantees about the stability of the master branch - for any stability guarantees, you'll have to use a tool that understands semantic versions. Glide, dep, govendor, and a variety of other options will all work.
