### ISSUE TITLE
Overriding registered implementations

### ISSUE THREAD

**Issue by amirov-m** [uber-go/dig#230]
Hello!
I would like to override already registered class instance with another one. For example in functional tests it is very useful to override registered instances. It seems like it is not possible to do that in current version. 

Are you planning to implement this feature in the future?

**Comment by glibsm** [comment]
There are a few discussions on this topic in the fx repo: https://github.com/uber-go/fx/issues/653 https://github.com/uber-go/fx/issues/653

**Comment by sywhang** [comment]
It's been a while since this issue was opened, but we just released v1.17.0 that contains the changes to modify the registered values of the dependency graph using `fx.Decorate` and `fx.Replace`. Will close this issue now - let me know if you have questions regarding the usage of these APIs.

**Comment by seanlafferty-ibm** [comment]
Would there still be any interest in adding this to dig? I don't need the full power of fx, but would still like to be able to replace services in dig when initializing tests.

I know fx is built on dig, maybe someone could share how `replace` is implemented in fx leveraging the existing dig constructs? That might be a fine workaround.

**Comment by seanlafferty-ibm** [comment]
Oh, dig can actually do this. The trick is making sure the function you pass to `decorate` is parameterless

https://github.com/uber-go/dig/blob/f02120a92598de12d0a93127beb9f60e3cf57bd3/decorate_test.go#L429-L449
