### ISSUE TITLE
Best practices?

### ISSUE THREAD

**Issue by nilskuhn** [uber-go/dig#232]
Hi there,

first thanks for providing this DI library!

But: I didn't find any documentation about how to use dig library, that goes beyond basic functionality. 
Mainly I wonder about the best way to provide DI container or even the container provided artifacts everywhere in my application. All I found were some blog posts showing a function in main package that provides the container and it's usage in main method. Something like this:
```
func GetDiContainer() *dig.Container {
	c := dig.New()
	c.Provide(this.NewThis)
	c.Provide(that.NewThat)
	return c
}
func main() {

	if err := GetDiContainer().Invoke(func(this this.ThisType, that that.ThatType) {

		package.needsThis(this)
		package.needsThat(that)

	}); err != nil {
		panic(err)
	}

}
```

DI frameworks I used to work with before (in other languages) provided a bit more convenience when accessing DI provided artifacts (by using reflection). How can I achieve this with dig? Should I just write a separate package providing the dig DI container? Should it be a singleton or do you instantiate another instance everywhere you need DI?

Thanks in advance for any hints about how to use dig in a larger project or even in several own packages.

Regards, Nils

**Comment by glibsm** [comment]
@nilskuhn hello, thanks for getting in touch.

It's likely that what you are looking for is https://github.com/uber-go/fx which is a framework built on top of dig. It's a specific way for how to use dig, if you will.

The docs are more comprehensive there as well: https://godoc.org/go.uber.org/fx.

Optimistically closing assuming that it resolves your question, but feel free to reopen if you have more questions.
