### ISSUE TITLE
Features: As & Replace

### ISSUE THREAD

**Issue by splokhikh** [uber-go/dig#248]
Guys, you library are really good. We are using it in our production microservices.
But it was a long time ago when you issued major version.

In real life we need some features, that already implemented, but not issued in major version (dig.As) and some features, that not implemented at all (like runtime Replace interface definition - we need it in testing purposes).

Many new libraries was issued since you last update, that already has this features. For example https://github.com/defval/inject

It would be great if you'll issue major version finally and include features listed above in this version.

Cheers!

**Comment by sywhang** [comment]
Found this issue while triaging some old issues in this repo. These features have shipped. 

dig.As was added in v1.13.0.

dig.Replace was added in v1.14.0.

I'll close this issue as done, but let me know if there are any questions.
