### ISSUE TITLE
Add support for scopes

### ISSUE THREAD

**Issue by mfateev** [uber-go/dig#249]
The basic idea is similar to the [Spring one](https://www.baeldung.com/spring-bean-scopes).

The strawman proposal is to support Container new that takes a parent container:

```
rootScope := dig.New()
rootScope.Provide(...)
// Execute per request
requestScope := rootScope.New()
requestScope.Provide(...)
requestScope.Invoke(...)
```
In the above example the requestScope container can use objects from rootScope as inputs.

Another option is to configure providers once and be able to reuse them, but it would require changing API to separate out the Container form ContainerConfig (which would solve the [copy issue ](https://github.com/uber-go/dig/issues/236)as well). Something like:

```
c := dig.New()
c.Provide(...)
g1 := c.NewObjectGraph()
g.Invoke(...)
g2 := c.NewObjectGraph()
```

**Comment by glibsm** [comment]
It sounds similar to what was proposed here as `fx.Module` https://github.com/uber-go/fx/issues/653#issuecomment-487641901

There are also some mentions of sub-graphs, and modifying graphs for things like unit testing.

Are you looking to get only this proposal approved, or also do the PR for it?

**Comment by mfateev** [comment]
https://github.com/uber-go/fx/issues/653 looks like what I want. Resolving as duplicate
