### ISSUE TITLE
dig: Provide-time introspection

### ISSUE THREAD

**Issue by abhinav** [uber-go/dig#254]
Currently, when you `c.Provide` a constructor to a dig container, you get no
visibility into what dig got out of it. If the constructor had a dig/fx.In
and/or a dig/fx.Out, the caller would have to implement its own reflection
logic to determine the list of actual types, named values, or value groups,
provided or consumed by that constructor. In fact, Fx has to do so already to
be able to log what was provided to each constructor.

I suggest that we add support for a means to extract information about the
provided constructor. It can take the form of a handle-style API which gives
us access to an object that represents a unique reference to the constructor
in the dig container, or it can take the form of an info-style API which
merely returns information it extracted.

To elaborate what I mean by that:

### Handle-style API

Under this API, we would expose a means of requesting a 'handle' to a
constructor into the container.

    var h dig.Handle
    c.Provide(constructor, dig.ProvideHandle(&h))
    
This handle would expose a means of introspection.

    h.ID()  // unique ID of the constructor in the container.
    h.Inputs()
    h.Outputs()
    
Theoretically, this could also expose a means of deletion and provide access
to the original constructor:

    h.Delete()

### Info-style API

In the Info-style API, we would only provide a means of introspection.

    var info dig.Info
    c.Provide(constructor, dig.ProvideInfo(&info))

    info.ID
    info.Inputs
    info.Outputs

----

Barring names, which are TBD, I don't have a strong preference between the
approaches, especially since nothing prevents us from providing both. Info
would be quicker to implement and exposes a smaller API surface, so perhaps
we should go for that first.

We can eventually provide accessors on errors returned by dig that point to
relevant constructors by their `Info/Handle` IDs.

Ref: T4578111

**Comment by sywhang** [comment]
Closed via #280
