### ISSUE TITLE
why not invoke  thread safe?  why not use tread safe map in Container, Below fatal err thorw when I  call invoke in two thread 

### ISSUE THREAD

**Issue by jack-yi** [uber-go/dig#258]
> fatal error: concurrent map writes

goroutine 35 [running]:
runtime.throw(0x580aae, 0x15)
	C:/Go/src/runtime/panic.go:774 +0x79 fp=0xc00007d768 sp=0xc00007d738 pc=0x42ee29
runtime.mapassign(0x54dc40, 0xc0000be690, 0xc00007d810, 0xc0000e4908)
	C:/Go/src/runtime/map.go:588 +0x5ca fp=0xc00007d7f0 sp=0xc00007d768 pc=0x40e26a
go.uber.org/dig.(*Container).setValue(0xc0000c4100, 0x0, 0x0, 0x5b1b20, 0x54f2e0, 0x54f2e0, 0xc0000c0250, 0x96)
	C:/Users/yiyb/go/pkg/mod/go.uber.org/dig@v1.8.0/dig.go:281 +0x8d fp=0xc00007d850 sp=0xc00007d7f0 pc=0x51309d
go.uber.org/dig.(*stagingContainerWriter).Commit(0xc0000bc310, 0xf60008, 0xc0000c4100)
	C:/Users/yiyb/go/pkg/mod/go.uber.org/dig@v1.8.0/dig.go:744 +0x120 fp=0xc00007d9d8 sp=0xc00007d850 pc=0x516ff0
go.uber.org/dig.(*node).Call(0xc0000dc0a0, 0x5b0d40, 0xc0000c4100, 0x5b1b20, 0x54f2e0)
	C:/Users/yiyb/go/pkg/mod/go.uber.org/dig@v1.8.0/dig.go:669 +0x3e2 fp=0xc00007db50 sp=0xc00007d9d8 pc=0x516382
go.uber.org/dig.paramSingle.Build(0x0, 0x0, 0x0, 0x5b1b20, 0x54f2e0, 0x5b0d40, 0xc0000c4100, 0x28, 0xc0000bf0e0, 0x566380, ...)
	C:/Users/yiyb/go/pkg/mod/go.uber.org/dig@v1.8.0/param.go:245 +0x35a fp=0xc00007dcf8 sp=0xc00007db50 pc=0x51ab9a
go.uber.org/dig.(*paramSingle).Build(0xc0000bf080, 0x5b0d40, 0xc0000c4100, 0xc0000c0120, 0xc0000bf0e0, 0xc0000f3df8, 0x516ac5, 0x5af4e0)
	<autogenerated>:1 +0xaa fp=0xc00007dd90 sp=0xc00007dcf8 pc=0x524fda
go.uber.org/dig.paramList.BuildList(0x5b1b20, 0x541800, 0xc0000bc270, 0x1, 0x1, 0x5b0d40, 0xc0000c4100, 0x0, 0x0, 0x0, ...)
	C:/Users/yiyb/go/pkg/mod/go.uber.org/dig@v1.8.0/param.go:201 +0xbf fp=0xc00007de08 sp=0xc00007dd90 pc=0x51a5df
go.uber.org/dig.(*Container).Invoke(0xc0000c4100, 0x541800, 0xc0000bc260, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Users/yiyb/go/pkg/mod/go.uber.org/dig@v1.8.0/dig.go:389 +0x2c1 fp=0xc00007df80 sp=0xc00007de08 pc=0x513e01
main.main.func2()
	C:/Users/yiyb/go/src/awesomeProject/main.go:70 +0x5e fp=0xc00007dfe0 sp=0xc00007df80 pc=0x526ebe
runtime.goexit()
	C:/Go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00007dfe8 sp=0xc00007dfe0 pc=0x457001
created by main.main
	C:/Users/yiyb/go/src/awesomeProject/main.go:66 +0x87

goroutine 1 [sleep]:
runtime.goparkunlock(...)
	C:/Go/src/runtime/proc.go:310
time.Sleep(0x77359400)
	C:/Go/src/runtime/time.go:105 +0x16c
main.main()
	C:/Users/yiyb/go/src/awesomeProject/main.go:92 +0x94

goroutine 34 [runnable]:
reflect.Value.assignTo(0x54f2e0, 0xc0000043d0, 0x96, 0x57fb0d, 0x12, 0x54f2e0, 0xc000006078, 0x0, 0x0, 0x28)
	C:/Go/src/reflect/value.go:2370 +0x43f
reflect.Value.call(0x541800, 0xc000034170, 0x13, 0x57cfa6, 0x4, 0xc0000042a0, 0x1, 0x1, 0x0, 0x0, ...)
	C:/Go/src/reflect/value.go:450 +0x9c9
reflect.Value.Call(0x541800, 0xc000034170, 0x13, 0xc0000042a0, 0x1, 0x1, 0xc0000c4100, 0xc0000042a0, 0x1)
	C:/Go/src/reflect/value.go:321 +0xbb
go.uber.org/dig.(*Container).Invoke(0xc0000c4100, 0x541800, 0xc000034170, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Users/yiyb/go/pkg/mod/go.uber.org/dig@v1.8.0/dig.go:397 +0x384
main.main.func1()
	C:/Users/yiyb/go/src/awesomeProject/main.go:55 +0x6f
created by main.main
	C:/Users/yiyb/go/src/awesomeProject/main.go:50 +0x6f

**Comment by jack-yi** [comment]
this is demo code

`func inject() {

	 _ = Container.Provide(func()string{
		return "yi"
	})

	err := Container.Provide(NewStudent)
	if err != nil {
		panic(err)
	}
}

func main() {
	Container = dig.New()
	inject()

	//locker := sync.RWMutex{}
	go func() {
		for i := 0; i < 100; i++ {
			//locker.Lock()
			var ss *Student
			fmt.Println(&ss)
			_ = Container.Invoke(func(s *Student) {
				ss = s
			})
			//locker.Unlock()
		}
	}()
	go func() {
		for i := 0; i < 100; i++ {
			//locker.Lock()
			var ss *Student
			_ = Container.Invoke(func(s *Student) {
				ss = s
			})
			//locker.Unlock()
		}
	}()

	time.Sleep(2 * time.Second)
}
`

**Comment by abhinav** [comment]
Hey, dig is not intended to be invoked from your system's hot path. We expect
it to be invoked at most once during startup, and definitely not concurrently.
To discourage usage on the hot path, we have kept the APIs thread-unsafe.

As a workaround, you can use a mutex yourself (as you've done in the example),
but we would recommend against invoking a container concurrently altogether.
See also #241 

Closing as Wontfix for now.
