### ISSUE TITLE
Slices and maps semantics in dependencies and return types

### ISSUE THREAD

**Issue by glibsm** [uber-go/dig#26]
Currently, dig only works with either a pointer to an object, or an interface. Slices and maps can sort be used by using a pointer to slice/map, or wrapping them in another struct.

Ideally, dig would support slices and maps as first class citizens. 

NOTE: there may be api implications for constructor parameters that are slices/maps. For example, if dig was handling the following constructor

```
func ([]typeA, typeB) typeC { }
```

What does it mean?
1. Does it mean that there is exactly one slice of type `[]typeA` registered in the graph and we should return that?
2. Does it mean there may be multiple constructors that return `func() typeA` or `func() []typeA` and we should fetch them all and put them into an slice?

Not handling case2 should probably be a starting point: there is only one slice of a given type that can live in the graph, we can deal with merging/extending existing slices through dig options in the future.

**Comment by alsamylkin** [comment]
Well, A and []A are different types, so we shouldn't do anything special to them.

As for option 1, we do have a different behavior in `fx.config`: for slices we replace and for maps we merge contents. I think it was inherited to support yaml merging though.

**Comment by akshayjshah** [comment]
A portion of this is addressed in #72.

**Comment by glibsm** [comment]
Value types are now supported, which makes all sorts of slices and maps work nicely with dig.

There are no special semantics for when two arrays are provided into the container - that would result in an error. Named instances, however, allow for a third constructor to come in and merge them together.
