### ISSUE TITLE
Remove Must* methods

### ISSUE THREAD

**Issue by breerly** [uber-go/dig#35]
The Must* methods provide a nice convenience for end users, but aren't necessary because:

DIG is not for end users. DIG should be used to build init/application frameworks.

Forcing init/app frameworks to explicitly manage errors means a reduced API surface, and overall simplified experience.

**Comment by glibsm** [comment]
I'm ok with this now, especially in light of us no longer having an interface where all the methods are consolidated together so you can get a comprehensive view of what the API looks like.

@peter-edge had an idea of creating a tool to easily see what the API looks like, and how a particular PR affects it, would definitely be useful for dig.

**Comment by glibsm** [comment]
Also, especially in light of us still having Register and Provide forms on methods we missed during the rename <insert homer dissapper gif>
