### ISSUE TITLE
dig.Container as a interface would be much easier to integrate

### ISSUE THREAD

**Issue by shyandsy** [uber-go/dig#363]
if the dig.Container is an interface, its much easier to integrate, right?
```
type AppContext interface {	
	//GetContainer() *dig.Container	
	dig.Container
}
```

this we can use all function from dig.Container as methods in AppContext

**Comment by shyandsy** [comment]
may be we can add a new way to use Dig as a interface

**Comment by sywhang** [comment]
My current thought on this is that we probably won't do this, as making an interface for this limits the extensibility of it. 

If we decide to support additional methods on the Container struct, adding such a method is not a breaking change. Adding a method to an interface, however, is a breaking change.

Given the tradeoffs, I believe Dig's current structure of returning the struct is a better design choice for us to continue iterating on more features.

Hope that makes sense.
