### ISSUE TITLE
1.0 API Surface

### ISSUE THREAD

**Issue by breerly** [uber-go/dig#37]
I think we are pretty close to a 1.0 API surface. To get there, I'd like to propose:

* `Container.Provide` - provide types into the container
* `Container.Resolve` - locate types out of the container

This streamlined API has a tiny surface, uses dependency injection terms in naming, and should prove easy to use for init/framework developers.

Here's what we should discuss:

* No more `Must*` funcs #35
* Remove `*All` funcs #40 
* Discuss combining `Resolve` and `Invoke`

**Comment by alsamylkin** [comment]
It would be nice to have minimal functions in the interface, but provide All/Must as helper functions, instead of part of the interface contract even inside e.g. the x package.

**Comment by breerly** [comment]
We're in a much better place now, closing this.
