### ISSUE TITLE
Remove *All funcs

### ISSUE THREAD

**Issue by breerly** [uber-go/dig#40]
Background #34 

In order to provide a tight API surface, let's remove the `*All` functions, leaving just:

* `Provide`
* `Resolve`
* `Invoke`

This will mean combining the `ProvideAll` and `ResolveAll` into `Provide` and `Resolve`, so that those functions deal with variadic arguments so they can operate on one or many deps.

**Comment by glibsm** [comment]
Before we commit to making all the functions `...interface{}`, I want us to pause for a second and think about the future functionality of dig, which we've been punting on: Options.

Whats an option? An option is something I envisioned reserved for named instances, private instances, things like that.

What I've envisioned in my head is something like this:

```
c.Provide(db, dig.Named("master"))
c.Resolve(db, dig.Named("secondary"))
c.Resolve(foo, dig.Private())
```

It is possible that we just start mixing and matching options into the `...interface{}` signature, but lets talk about it at least at the high level before we put the API to the axe

**Comment by anuptalwalkar** [comment]
I have a suggestion for naming, however it doesn't work for constructors or invoke - 

Add naming indirection to the graph, so internally it will change to this -
```go
nodes map[reflect.Type][string]graphnode
```

what does this mean? 
```
for registered variable xyz - 
```go
var xyz *string
c.Provide(xyz)
```
graph nodes will look like - 
```go
reflect.String: 
  "xyz": reflect.ValueOf(xyz)
```
resolve will be based on object name
to fetch the provided string, variable name must be 'xyz'
```go
var xyz *string
c.Resolve(&xyz)
```
If naming is not provided, default object indirection can be an empty string - ""

I am having hard time explaining, and may be a prototype non mergable PR will be helpful. Will write down something nicely.

**Comment by breerly** [comment]
@glibsm it's a good point.

I think I'd like to lean on separate entry-points for specialized cases. For example:

```
c.ProvideNamed("master", db)
c.ResolveNamed("master", db)
```

Do you buy that?

**Comment by glibsm** [comment]
So what if we wanted private instances for which a constructor is called every time, would we add another entry point called `ResolvePrivate(foo)`?

Didn't we just spend most of the day talking about reducing the surface level of the API? :)

I'm not trying to use your words against you, I'm just trying to think through what the API is going to look like in version 3.0 if/when we support things like named params, private instances, or even factories on a more generic level.

**Comment by breerly** [comment]
I'm actually coming to the thinking that we don't need to natively support naming or private.

Sometimes less is infinitely more - I think, out of all the dependency injection frameworks I've seen and worked with, having a small API and feature set could have enabled most of the power features of "big" frameworks.

I think this might be the right balance for Go, and we'll be able to build an init framework with this.

For these power features, I'd really like to see us backed into a corner before figuring out how to add them to dig.

**Comment by glibsm** [comment]
Btw, I'm not arguing about the removal of *All functions per say, I think it's a good thing. FWIW next time I come across something similar I need to create I should call it more like what it was `ResolveEACH`, since people presumed `ResolveAll` is just a no-op to resolve *all the objects in the graph*, i.e. cache everything and be ready to return right away!

**Comment by anuptalwalkar** [comment]
Resolving/Providing named objects is tricky since we will never be able to resolve dependencies in constructor for "named" objects, atleast with go ^1.0. I have removed All functions and added variadic arguments support in #41. 
IMO, If/When we add naming, it should be very convenient to use and not add overhead of coming up with naming system for users.
