### ISSUE TITLE
Drop all the locks?

### ISSUE THREAD

**Issue by glibsm** [uber-go/dig#46]
Now that dig is completely hidden from the user's eye through fx, I think one of the suggestions was to drop all the locks, I'm guessing with the assumption that it makes the dig implementation code simpler.

I'm all for making dig internals as clear as possible, but please let me know your thoughts around this @breerly @anuptalwalkar

**Comment by breerly** [comment]
Seeing how we intend dig to be used to power serial object-graph resolution at process-startup time, I'm in favor of simplifying.

If we do need it, great. Until then, I'm ok w leaning on YAGNI. I'd like Anup to be onboard with this in spirit.

**Comment by breerly** [comment]
What I meant was, I want to make sure Anup is onboard in spirit before we go one way or another :)

**Comment by anuptalwalkar** [comment]
Well, locks are not that complex right now and hidden from front APIs. I am ok with removing this as long as we make sure not to expose dig outside, or to multiple go routines. Of course we can add it back if needs be:)
