### ISSUE TITLE
Invoke on provided/unprovided ctors

### ISSUE THREAD

**Issue by anuptalwalkar** [uber-go/dig#48]
Calling `Invoke` on provided and unprovided funcs can result in executing constructors more than once and overwriting the graph with the resulted return objects.
for provided constructors - 
 ```
ctor1(a *A, b *B) (x *x)
ctor2() (a *A)
```
Invoking constructors in order will result in ctor1 resolving *A and *B. 
Invoking ctor2 will result in resolving *A again.

**Comment by anuptalwalkar** [comment]
Here, execution is not the problem since the call can contain critical code, or functions that we Invoke multiple times. We have few choices - 
1. Don't Invoke function if return type is registered in the graph. `Invoke` will ignore the function and continue.

2. Error out on `Invoke` call if return types are already registered. (However, this will enforce required order in which functions must be Invoke'd.

3. `Invoke` the function. Register only values that are absent in the graph. Ignore already registered values and avoid overwriting.

4. Execute Invoke function every time and only fail on provided option. We can introduce `InvokeOption` to perform following - 
- Provide return types on function execution, overwrite is allowed (`Provide=true`)
- Ignore return types on function execution (`Provide=false`)
- Force an `error` if return type is already provided to the graph (Force = true)

As a default, 
`Provide = true` - always overwrite if not specified
`Force = false` - overwrite and don't return error

**Comment by anuptalwalkar** [comment]
@breerly @glibsm thoughts? 
I am split between Option 1 and 4, but leaning towards 4.
Option 1 will keep a clean API, except it will add reentrant characteristic to Invoke. This means your function might not execute if return parameter is registered in dig, and will lead to strange behavior.
Option 4 is more explicit with InvokeOptions (similar to zap's options) and can extend Invoke's use case in the future.

**Comment by alsamylkin** [comment]
I'd rather keep the Invoke as is, but provide a wrapper, dig.Once:
```golang
func Once(ctor dig.Fn) dig.Fn {
  tp := reflect.TypeOf(ctor)
  if tp.Kind() != reflect.Func {
    panic("expect function to listen")
  }

  ctorVal := reflect.ValueOf(ctor)
  listenerVal := reflect.ValueOf(listener)
  execute := true
  outs := []reflect.Value
  res := reflect.MakeFunc(tp, func(args []reflect.Value) []reflect.Value {
    if execute {
       outs = ctorVal.Call(args)
       execute = false
    }
    return outs
  })

  return res.Interface()
}
```

**Comment by breerly** [comment]
Actually agreed w/ @alsamylkin for now, but would like to see the funcs named:

* `Container.Invoke`
* `Container.InvokeOnce`

**Comment by anuptalwalkar** [comment]
Interesting. I can add a wrapper and associate with proper error message. 

```go
func (c *Container) InvokeOnce(t interface{}) error {
	ctype := reflect.TypeOf(t)
	if ctype.Kind() != reflect.Func {
		panic("")
	}
	if err := c.ValidateReturnTypes(ctype); err != nil {
		return err
	}
	return c.Invoke(t)
}
```

**Comment by alsamylkin** [comment]
I was actually trying to avoid expanding the API :) A simple helper function, that wraps the user function should suffice.

**Comment by anuptalwalkar** [comment]
I would love to avoid adding new API, but having InvokeOnce API will allow us to simplify functionality for its use outside dig. I don't like global Once API on dig package since it convolutes how we use dig today (via container). 

That being said, we can have a `InvokeOnce` API that returns a strongly typed error `dig.ErrInvokeOnce` and let the caller choose what to do with that error. (log it or ignore it or panic).

**Comment by alsamylkin** [comment]
What globals do you mean? Everything is local and organic:
```golang
func (s *Service) Provide(cs ...Constructor) {
	for _, c := range cs {
		ctor := once(c)
		s.constructors = append(s.constructors, once(ctor))
		err := s.container.Provide(ctor)
		if err != nil {
			log.Panicf("Err providing constructor: %v", err)
		}
	}
}
```
This function is needed only for Fx's naughty cases and Fx can have it(and keep it private). If users want this functionality, we can make it public later.

**Comment by anuptalwalkar** [comment]
I don't know what you mean by naughty cases. I believe this functionality exist to work on any cyclic dependencies the code can introduce. So by providing to graph, we can resolve them in any order we want. InvokeOnce will be called later in start on these provided ctors. If we remove not providing here, we will need ctor order from service owners in which Invoke is called.

**Comment by alsamylkin** [comment]
Ok, I had a misunderstanding what invoke is doing, I thought we didn't want to register its results in the graph.

**Comment by akshayjshah** [comment]
Is this still relevant?

**Comment by akshayjshah** [comment]
This appears to be irrelevant with the direction we've gone, so I'm going to close it.
