### ISSUE TITLE
No panics

### ISSUE THREAD

**Issue by breerly** [uber-go/dig#51]
Dig should *always* return `errs` so that FX can control what those `errs` mean.

**Comment by glibsm** [comment]
dig doesn't panic?

```
ag panic
container.go
138:                            err = fmt.Errorf("panic during Resolve %v", r)

container_test.go
520:func TestPanicConstructor(t *testing.T) {
526:            panic("RUH ROH")
533:    require.Contains(t, err.Error(), "panic during Resolve")

examples/three/three.go
60:             panic(err)
67:             panic(err)
```

**Comment by glibsm** [comment]
we could even add the same panic recovery system to `Invoke` as well

**Comment by breerly** [comment]
Ok - so we never panic, that's great.

I'm actually not sure if we should recover other panics TBH, but that's a separate concern.

**Comment by glibsm** [comment]
> I'm actually not sure if we should recover other panics 

The initial idea was to add them to cover reflect specific errors - it tend to panic a lot. 

But now that I think about it, we're also going to catch panics in constructors -- and we will return an error. And you're right, that might not be desired. Lets talk about it in another thread to see if we should drop that
