### ISSUE TITLE
Try out codecov.io

### ISSUE THREAD

**Issue by glibsm** [uber-go/dig#53]
I'd love to get in-lined coverage information on PRs. I don't have a particular preference for which service is going to provide it, but seems like other OSS projects are using codecov and it's working well.

**Comment by glibsm** [comment]
This might be useful https://github.com/uber-go/config/pull/6

**Comment by breerly** [comment]
Anything I can do to help out w this?

**Comment by abhinav** [comment]
Resolved by #85
