### ISSUE TITLE
Providing the same type twice should err

### ISSUE THREAD

**Issue by breerly** [uber-go/dig#58]
Currently providing the same type twice overwrites the original type.

This is going to lead to tons of difficult to understand and debug issues, resulting in our customers swarming our help channels and generally being not happy.

Instead, let's clamp down on this early and err if the same type is provided once. That way we won't get in the habit of abusing this, instead we'll be forced to develop more explicit patterns.

**Comment by glibsm** [comment]
@anuptalwalkar has this already been merged or it this part of #55 ?

**Comment by anuptalwalkar** [comment]
yes. no overwriting on Provide. Its actually PR #49
