### ISSUE TITLE
Only support Providing constructors

### ISSUE THREAD

**Issue by akshayjshah** [uber-go/dig#74]
The current `Provide` API supports passing both instances and constructors. That is, if I want `*Foo` available in the graph, I can do either `Provide(func() *Foo {return &Foo{}})` *or* I can do `Provide(&Foo{})` directly.

This is sometimes really convenient, since it removes the need for some anonymous shim functions in modules. Unfortunately, it also introduces a number of inconsistencies. These inconsistencies all make sense if you understand Go's type system and reflection capabilities well, but I suspect that they'll be very confusing to users. I've highlighted some examples in integration tests: see [this note about providing functions](https://github.com/uber-go/dig/pull/70/files#diff-57b62c4de3de7448fc388611a7ade598R168), [this one about interfaces](https://github.com/uber-go/dig/pull/70/files#diff-57b62c4de3de7448fc388611a7ade598R181), and [this one about errors](https://github.com/uber-go/dig/pull/70/files#diff-57b62c4de3de7448fc388611a7ade598R266).

Because functions carry more reflect-able type information with them, providing constructors doesn't have any of these issues.

I suspect that these inconsistencies (especially the one about providing interface instances) will require a lot of detailed documentation and will prompt a lot of support requests. At least for Fx's initial launch, let's *consider* only supporting constructors.

**Comment by breerly** [comment]
I'm onboard - less is infinitely more.

We can always add instance support back, but we can't 1.0 with it and take it away.

I know we dont need it in Fx, at least not initially, and I suspect we won't miss it at all.

**Comment by abhinav** [comment]
Sounds good to me. We can always add it back later.

**Comment by glibsm** [comment]
Apart from removing ambiguity, it will also let us clean up the internals of dig, since we switch on function/object in several places.

**Comment by akshayjshah** [comment]
I can open a PR for this today. If everyone's happy with the end result, let's close this out.

**Comment by glibsm** [comment]
Resolved in #98
